name: Deploy to MS environment on push to main

on:
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'

jobs:
  Initial-deployment-check-pull-request:
      runs-on: ubuntu-latest
      environment: Srims
      steps:
          - uses: actions/setup-node@v4
            with:
              node-version: '18'
          - name: 'Checkout source code'
            uses: actions/checkout@v4
            with:
              fetch-depth: '2'
                
          # Now Install Salesforce CLI
          - name: 'Install sfdx'
            run: npm install @salesforce/cli --global
          - name: 'Installing sfdx git delta'
            run: | 
                echo Y | sfdx plugins:install sfdx-git-delta
                sfdx plugins

           # Install java as it is required for the next step
          - name: 'Installing java'
            run: |
                sudo apt-get update
                sudo apt install default-jdk

          # Install SFDX scanner
          - name: 'Installing SFDX scanner'
            run: sfdx plugins:install @salesforce/sfdx-scanner

          - name: 'Create delta packages'
            run: | 
                mkdir changed-sources
                sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
                echo "[INFO] Diff generated"

          - name: 'Upload delta package as artifact'
            uses: actions/upload-artifact@v4
            with:
              name: 'delta-package'
              path: changed-sources/
                
          - name: 'Deploy to environment with running all local tests'
            run: |
                echo "${{ secrets.SF_JWT_SECRET_KEY }}" > server.key
                sf org login jwt --username ${{ secrets.SF_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.SF_CLIENT_CONSUMER_ID }} --instance-url ${{ vars.SF_INSTANCE_URL }} --set-default


          - name: 'Scan code'
            run: |
                  cd changed-sources
                  sfdx scanner:run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'  
                  cd ..

          # Now we upload the .sarif file as explained in the previous step
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: changed-sources/apexScanResults.sarif
          #sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests
          - name: Deploy changes 
            run: |
                  sfdx force:source:deploy -p "changed-sources/force-app" --checkonly --testlevel RunLocalTests  --json > test-results.json


          - name: Upload test results
            uses: actions/upload-artifact@v4
            with:
              name: test-results
              path: test-results.json
